name: Run test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Vet code
        run: go vet ./...

      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38

      - name: run test
        run: ./test.sh

      - name: Export coverage result
        run: bash <(curl -s https://codecov.io/bash)