name: test

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Vet and lint code
      run: |
        go get -u -v golang.org/x/lint/golint
        /home/runner/go/bin/golint -set_exit_status ./...
        go vet ./...

    - name: run test 
      run: ./test.sh
    
    - name: Export coverage result 
      run: bash <(curl -s https://codecov.io/bash)