name: Run test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Vet code
        run: go vet ./...

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

      - name: run test
        run: ./test.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          path_to_write_report: ./codecov_report.txt